package ru.itmo.tpo3.firefox;// Generated by Selenium IDE

import org.junit.After;
import org.junit.Before;
import org.junit.Test;
import org.openqa.selenium.*;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.firefox.FirefoxDriver;

import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Set;

public class OpenPicturesInMainPageTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    System.setProperty("webdriver.gecko.driver", "C:\\drivers\\geckodriver.exe");
    System.setProperty("webdriver.firefox.marionette","D:\\drivers\\geckodriver.exe");
    driver = new FirefoxDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  public String waitForWindow(int timeout) {
    try {
      Thread.sleep(timeout);
    } catch (InterruptedException e) {
      e.printStackTrace();
    }
    Set<String> whNow = driver.getWindowHandles();
    Set<String> whThen = (Set<String>) vars.get("window_handles");
    if (whNow.size() > whThen.size()) {
      whNow.removeAll(whThen);
    }
    return whNow.iterator().next();
  }
  @Test
  public void openPicturesInMainPage() {
    driver.get("http://angely-sveta.ru/russian/");
    driver.manage().window().setSize(new Dimension(866, 622));
    driver.findElement(By.cssSelector("img")).click();
    driver.findElement(By.cssSelector("img")).click();
    driver.findElement(By.cssSelector("img")).click();
    driver.switchTo().frame(1);
    vars.put("window_handles", driver.getWindowHandles());
    driver.findElement(By.xpath("//table[12]/tbody/tr/td/a/img")).click();
    vars.put("win4918", waitForWindow(2000));
    vars.put("root", driver.getWindowHandle());
    driver.switchTo().window(vars.get("win4918").toString());
    {
      List<WebElement> elements = driver.findElements(By.cssSelector("img"));
      assert(elements.size() > 0);
    }
    driver.close();
    driver.switchTo().window(vars.get("root").toString());
    driver.switchTo().frame(1);
    vars.put("window_handles", driver.getWindowHandles());
    driver.findElement(By.xpath("//table[13]/tbody/tr/td/a/img")).click();
    vars.put("win2470", waitForWindow(2000));
    driver.switchTo().window(vars.get("win2470").toString());
    {
      List<WebElement> elements = driver.findElements(By.cssSelector("img"));
      assert(elements.size() > 0);
    }
    driver.close();
    driver.switchTo().window(vars.get("root").toString());
    driver.close();
  }
}
