package ru.itmo.tpo3.chrome;// Generated by Selenium IDE

import org.junit.After;
import org.junit.Before;
import org.junit.Test;
import org.openqa.selenium.*;
import org.openqa.selenium.chrome.ChromeDriver;

import java.util.HashMap;
import java.util.List;
import java.util.Map;

public class CheckFirstPictureTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    System.setProperty("webdriver.chrome.driver", "C:\\drivers\\chromedriver.exe");
    System.setProperty("webdriver.http.factory", "jdk-http-client");
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void checkFirstPicture() {
    driver.get("http://angely-sveta.ru/russian/");
    driver.manage().window().setSize(new Dimension(866, 622));
    {
      List<WebElement> elements = driver.findElements(By.xpath("//img[@alt=\' Next \']"));
      assert(elements.size() > 0);
    }
  }
}
