package ru.itmo.tpo3.chrome;// Generated by Selenium IDE

import org.junit.After;
import org.junit.Before;
import org.junit.Test;
import org.openqa.selenium.By;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeDriver;

import java.util.HashMap;
import java.util.Map;

public class CheckEvacuationDownloadingTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    System.setProperty("webdriver.chrome.driver", "C:\\drivers\\chromedriver.exe");
    System.setProperty("webdriver.http.factory", "jdk-http-client");
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void checkEvacuationDownloading() {
    driver.get("http://angely-sveta.ru/russian/default_ru.htm");
    driver.manage().window().setSize(new Dimension(866, 622));
    driver.switchTo().frame(1);
    driver.findElement(By.cssSelector("table:nth-child(1) a > img")).click();
    driver.switchTo().frame(0);
    driver.findElement(By.linkText("EVACUATION - Part 1 of 7")).click();
  }
}
